--assert(SMODS.load_file('items/Jokers/Jokers/summersend.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/tsunova.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/mineturtle.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/sleeplessnights.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/intertwiningluck.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/hauntinglysweetvices.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/dacnovania.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/nomorenuzzles.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/cookiecat.lua'))()
--assert(SMODS.load_file('items/Jokers/Jokers/luckylucy.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/burrowingbangboo.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/candyblossom.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/candyblossomtree.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/divine.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/uneducatedguess.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/risingshine.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/markeddownmerchandise.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/chibimita.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/kindmita.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/backalleyboning.lua'))()
-- assert(SMODS.load_file('items/Jokers/Jokers/Jealousy.lua'))()
-- assert(SMODS.load_file('items/Jokers/Jokers/overloadedsnacking.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/fourofakind.lua'))()
assert(SMODS.load_file('items/Jokers/Jokers/fanfarefever.lua'))()